In [2]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
import cv2
from PIL import Image

In [3]:
from keras.models import load_model

In [4]:
face_extract = cv2.CascadeClassifier('haarcasacde_facefrontal_default.xml')

In [16]:
def return_face(img):
    face = face_extract.detectMultiScale(img,1.3,5)
    if face is ():
        return []
    else:
        cropped_face = []
        for (x,y,w,h) in face :
            x = x - 10
            y = y - 10
            cropped_face.append(img[y:y+h+50 , x:x+w+50])
        return cropped_face[0]

<>:3: SyntaxWarning: "is" with a literal. Did you mean "=="?
<>:3: SyntaxWarning: "is" with a literal. Did you mean "=="?
<ipython-input-16-ae54d9b249b1>:3: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if face is ():


In [17]:
model = load_model('model_vgg.h5')

In [20]:
video_capture = cv2.VideoCapture(0)
while True:
    _, frame = video_capture.read()
    #canvas = detect(gray, frame)
    #image, face =face_detector(frame)
    
    face=return_face(frame)
    if type(face) is np.ndarray:
        face = cv2.resize(face, (224, 224))
        im = Image.fromarray(face, 'RGB')
           #Resizing into 128x128 because we trained the model with this image size.
        img_array = np.array(im)
                    #Our keras model used a 4D tensor, (images x height x width x channel)
                    #So changing dimension 128x128x3 into 1x128x128x3 
        img_array = np.expand_dims(img_array, axis=0)
        pred = model.predict(img_array)
        print(pred)
                     
        name="None matching"
        
        if(pred[0][0]>0.5):
            name='Aryan'
            cv2.putText(frame,name, (50, 50), cv2.FONT_HERSHEY_COMPLEX, 1, (0,255,0), 2)
        elif(pred[0][1]>0.5):
            name='Manoj'
            #cv2.rectangle(img,(x,y), (x+w,y+h), (0,255,0), 2)
            cv2.putText(frame,name, (50, 50), cv2.FONT_HERSHEY_COMPLEX, 1, (0,255,0), 2)
        elif(pred[0][2]>0.5):
            name='Shilpa'
            cv2.putText(frame,name, (50, 50), cv2.FONT_HERSHEY_COMPLEX, 1, (0,255,0), 2)
    else:
        cv2.putText(frame,"No face found", (50, 50), cv2.FONT_HERSHEY_COMPLEX, 1, (0,255,0), 2)
    cv2.imshow('Video', frame)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break
video_capture.release()
cv2.destroyAllWindows()

[[0. 0. 1.]]
[[1. 0. 0.]]
[[0. 0. 1.]]
[[1. 0. 0.]]
[[1. 0. 0.]]
[[1.0471526e-21 0.0000000e+00 1.0000000e+00]]
[[1. 0. 0.]]
[[0. 0. 1.]]
[[1. 0. 0.]]
[[0. 0. 1.]]
[[0. 0. 1.]]
[[1. 0. 0.]]
[[1. 0. 0.]]
[[0. 0. 1.]]
[[1. 0. 0.]]
[[0. 0. 1.]]
[[0. 0. 1.]]
[[0. 0. 1.]]
[[0. 0. 1.]]
[[0. 0. 1.]]
[[0. 0. 1.]]
[[1. 0. 0.]]
[[1. 0. 0.]]
[[0. 0. 1.]]
[[1. 0. 0.]]
[[0. 0. 1.]]
[[0. 0. 1.]]
[[0. 0. 1.]]
[[1. 0. 0.]]
[[0. 0. 1.]]
[[0. 0. 1.]]
[[0. 0. 1.]]


KeyboardInterrupt: 

In [21]:
video_capture.release()